AWSTemplateFormatVersion: 2010-09-09
Resources:
  myStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/stacknested329329/s3static.json'
      TimeoutInMinutes: '60'
  myStack2:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/stacknested329329/noretain.json'
      TimeoutInMinutes: '60'

